// js/csv_column_headers.js

export const CSV_HEADERS = {
  CENTRO_DE_CUSTO: "CENTRO DE CUSTO",
  OBJETO: "OBJETO",
  N_PROCESSO_CONTRATO: "Nº PROCESSO CONTRATO",
  CONTRATO: "CONTRATO",
  ORGAO: "ÓRGÃO",
  MUNICIPIO: "MUNICIPIO",
  STATUS: "STATUS",
  ORDEM_INICIO: "ORDEM INICIO",
  PRAZO_EXECUCAO: "PRAZO EXECUÇÃO",
  TERMINO: "TERMINO",
  PRIMEIRA_RENOVACAO: "1ª RENOVAÇÃO", // Para "1ª RENOVAÇÃO"
  PARALISACAO: "PARALISAÇÃO",
  SUSPENSAO: "SUSPENSÃO",
  REINICIO: "REINICIO",
  PRIMEIRO_ANIVERSARIO_REAJUSTE: "1º ANIVERSÁRIO REAJUSTE", // Para "1º ANIVERSÁRIO REAJUSTE"
  SEGUNDO_ANIVERSARIO_REAJUSTE: "2º ANIVERSÁRIO REAJUSTE",
  TERCEIRO_ANIVERSARIO_REAJUSTE: "3º ANIVERSÁRIO REAJUSTE",
  QUARTO_ANIVERSARIO_REAJUSTE: "4º ANIVERSÁRIO REAJUSTE",
  QUINTO_ANIVERSARIO_REAJUSTE: "5º ANIVERSÁRIO REAJUSTE",
  CRONOGRAMA_INICIAL_R$: "CRONOGRAMA INICIAL (R$)",
  CRONOGRAMA_ATUALIZADO_PERCENT: "CRONOGRAMA ATUALIZADO (%)", // Para "CRONOGRAMA ATUALIZADO (%)"
  READEQUACAO_CRONOGRAMA_R$: "READEQUAÇÃO CRONOGRAMA (R$)",
  MEDICAO: "MEDIÇÃO",
  PERIODO: "PERIODO",
  EXECUTADO_R$: "EXECUTADO (R$)",
  EXECUTADO_PERCENT: "EXECUTADO (%)", // Para "EXECUTADO (%)"
  DATA_PROTOCOLO: "DATA PROTOCOLO",
  NF: "NF",
  N_PROCESSO1: "Nº PROCESSO1",
  LEGENDA: "LEGENDA",
  STATUS2: "STATUS2",
  DATA_PAGT: "DATA PAGTº", // Para "DATA PAGTº"
  VALOR_PAGO: "VALOR PAGO",
  N_EMPENHO: "Nº EMPENHO",
  R$_EMPENHO: "R$ EMPENHO", // Para "R$ EMPENHO"
  SALDO_DE_EMPENHO: "SALDO DE EMPENHO",
  PRATELEIRA: "PRATELEIRA",
  PERCENT: "%", // Para "%"
  REAJUSTE_R$: "REAJUSTE(R$)",
  DATA_PROTOCOLO_2PONTOS: "DATA PROTOCOLO..", // Para "DATA PROTOCOLO.."
  NF2: "NF2",
  N_PROCESSO2: "Nº PROCESSO2",
  LEGENDA2: "LEGENDA2",
  STATUS3: "STATUS3",
  DATA_PAGT_PONTO: "DATA PAGTº.", // Para "DATA PAGTº."
  VALOR_PAGO_PONTO: "VALOR PAGO.", // Para "VALOR PAGO."
  ADITIVO_PERCENT: "ADITIVO  - (%)", // Mantendo o espaço duplo antes do traço conforme sua lista
  ADITIVO_R$: "ADITIVO  - (R$)", // Mantendo o espaço duplo antes do traço conforme sua lista
  DATA_PROTOCOLO_PONTO: "DATA PROTOCOLO.", // Para "DATA PROTOCOLO."
  N_PROCESSO: "Nº PROCESSO", // Este é o 50º item, distinto dos outros "Nº PROCESSO..."
  STATUS4: "STATUS4",
  IMPOSTO_20_PERCENT: "IMPOSTO (20%) ", // Mantendo espaço no final se estiver no seu CSV
  RECEBIDO_ESPACO: "RECEBIDO ", // Mantendo espaço no final
  CUSTO_ESPACO: "CUSTO ", // Mantendo espaço no final
  ADM_5_PERCENT: "ADM (5%) ", // Mantendo espaço no final
  RESULTADO_ESPACO: "RESULTADO ", // Mantendo espaço no final
  PERCENT_2: "2%", // Para "2%"
  DIRETOR: "DIRETOR",
  GERENTE: "GERENTE",
};